### ISSUE TITLE
Server log callback is not set - missing feature?

### ISSUE THREAD

**Issue by pszabop** [rkrishn7/rust-modsecurity#12]
`Server log callback is not set -- [client ] ModSecurity: Warning. detected XSS using libinjection. [file "/usr/share/modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "38"] [id "941100"] [rev ""] [msg "XSS Attack Detected via libinjection"] [data "Matched Data: XSS data found within ARGS:q: \x22><script>alert(1)</script>"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname ""] [uri "/"] [unique_id "17249538617.252121"] [ref "v8,27t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls"] [hostname ""] [uri "/"] [unique_id "17249538617.252121"]`

this appears to be a different callback than the one provided in the `transaction_builder`?.  I have that installed (and oddly enough it's not getting a callback).

the setup is

1. the default `crs-setup.conf` rule file loaded from `modsecurity-crs` package.
2. All the REQUEST `.conf` rule files loaded
3. `curl -i 'localhost:6189?q="><script>alert(1)</script>"`

code that installs a logger callback:
```
        let mut transaction = self.ms
            .transaction_builder()
            .with_rules(&self.rules)
            .with_logging(|msg| {
                if let Some(msg) = msg {
                    println!("Received log callback: {}", msg);
                } else {
                    println!("no message on logging callback");
                }
            })  
            .build()
            .expect("Error building transaction");

```

**Comment by rkrishn7** [comment]
Hey @pszabop,

Are you enabling log callbacks with `ModSecurityBuilder`?

See: https://docs.rs/modsecurity/latest/modsecurity/msc/struct.ModSecurityBuilder.html#method.with_log_callbacks

**Comment by pszabop** [comment]
nope.  how embarrassing
